package com.bar3.hibernateDemo4;

// Generated 2016-2-10 19:40:41 by Hibernate Tools 4.3.1

/**
 * ClassE generated by hbm2java
 */
public class ClassE extends com.bar3.hibernateDemo4.ClassB implements java.io.Serializable {

	private String e1;
	private String e2;
	private String e3;
	private String e4;
	private String e5;
	private String e6;

	public ClassE() {
	}

	public ClassE(String b1, String e1, String e2, String e3, String e4, String e5, String e6) {
		super(b1);
		this.e1 = e1;
		this.e2 = e2;
		this.e3 = e3;
		this.e4 = e4;
		this.e5 = e5;
		this.e6 = e6;
	}

	public String getE1() {
		return this.e1;
	}

	public void setE1(String e1) {
		this.e1 = e1;
	}

	public String getE2() {
		return this.e2;
	}

	public void setE2(String e2) {
		this.e2 = e2;
	}

	public String getE3() {
		return this.e3;
	}

	public void setE3(String e3) {
		this.e3 = e3;
	}

	public String getE4() {
		return this.e4;
	}

	public void setE4(String e4) {
		this.e4 = e4;
	}

	public String getE5() {
		return this.e5;
	}

	public void setE5(String e5) {
		this.e5 = e5;
	}

	public String getE6() {
		return this.e6;
	}

	public void setE6(String e6) {
		this.e6 = e6;
	}

}
