package com.bar3.hibernateDemo4;

// Generated 2016-2-10 19:40:41 by Hibernate Tools 4.3.1

/**
 * ClassD generated by hbm2java
 */
public class ClassD extends com.bar3.hibernateDemo4.ClassA implements java.io.Serializable {

	private String d1;

	public ClassD() {
	}

	public ClassD(String a1, String d1) {
		super(a1);
		this.d1 = d1;
	}

	public String getD1() {
		return this.d1;
	}

	public void setD1(String d1) {
		this.d1 = d1;
	}

}
