package com.bar3.hibernateDemo4;

// Generated 2016-2-10 19:40:41 by Hibernate Tools 4.3.1

/**
 * ClassG generated by hbm2java
 */
public class ClassG extends com.bar3.hibernateDemo4.ClassD implements java.io.Serializable {

	private String g1;

	public ClassG() {
	}

	public ClassG(String a1, String d1, String g1) {
		super(a1, d1);
		this.g1 = g1;
	}

	public String getG1() {
		return this.g1;
	}

	public void setG1(String g1) {
		this.g1 = g1;
	}

}
