package com.bar3.hibernateDemo4;

// Generated 2016-2-10 19:40:41 by Hibernate Tools 4.3.1

/**
 * ClassC generated by hbm2java
 */
public class ClassC extends com.bar3.hibernateDemo4.ClassA implements java.io.Serializable {

	private String c1;

	public ClassC() {
	}

	public ClassC(String a1, String c1) {
		super(a1);
		this.c1 = c1;
	}

	public String getC1() {
		return this.c1;
	}

	public void setC1(String c1) {
		this.c1 = c1;
	}

}
