package com.bar3.hibernateDemo4;

// Generated 2016-2-10 19:40:41 by Hibernate Tools 4.3.1

/**
 * ClassH generated by hbm2java
 */
public class ClassH extends com.bar3.hibernateDemo4.ClassD implements java.io.Serializable {

	private String h1;

	public ClassH() {
	}

	public ClassH(String a1, String d1, String h1) {
		super(a1, d1);
		this.h1 = h1;
	}

	public String getH1() {
		return this.h1;
	}

	public void setH1(String h1) {
		this.h1 = h1;
	}

}
