package com.bar3.hibernateDemo;

// Generated 2016-2-7 13:28:22 by Hibernate Tools 4.3.1

/**
 * Address generated by hbm2java
 */
public class Address implements java.io.Serializable {

	private String province;
	private String city;
	private String street;
	private String zipCode;

	public Address() {
	}

	public Address(String province, String city, String street, String zipCode) {
		this.province = province;
		this.city = city;
		this.street = street;
		this.zipCode = zipCode;
	}

	public String getProvince() {
		return this.province;
	}

	public void setProvince(String province) {
		this.province = province;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getStreet() {
		return this.street;
	}

	public void setStreet(String street) {
		this.street = street;
	}

	public String getZipCode() {
		return this.zipCode;
	}

	public void setZipCode(String zipCode) {
		this.zipCode = zipCode;
	}

}
