package com.bar3.hibernateDemo;

// Generated 2016-2-7 13:28:22 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * AuditLogRecord generated by hbm2java
 */
public class AuditLogRecord implements java.io.Serializable {

	private String message;
	private long entityId;
	private Class entityClass;
	private Date created;

	public AuditLogRecord() {
	}

	public AuditLogRecord(String message, long entityId, Class entityClass, Date created) {
		this.message = message;
		this.entityId = entityId;
		this.entityClass = entityClass;
		this.created = created;
	}

	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	public long getEntityId() {
		return this.entityId;
	}

	public void setEntityId(long entityId) {
		this.entityId = entityId;
	}

	public Class getEntityClass() {
		return this.entityClass;
	}

	public void setEntityClass(Class entityClass) {
		this.entityClass = entityClass;
	}

	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

}
