package com.bar3.hibernateDemo;

// Generated 2016-2-7 13:50:38 by Hibernate Tools 4.3.1

/**
 * CpuBox generated by hbm2java
 */
public class CpuBox implements java.io.Serializable {

	private String type;
	private GraphicsCard graphicsCard;
	private Vendor vendor;

	public CpuBox() {
	}

	public CpuBox(Vendor vendor) {
		this.vendor = vendor;
	}

	public CpuBox(String type, GraphicsCard graphicsCard, Vendor vendor) {
		this.type = type;
		this.graphicsCard = graphicsCard;
		this.vendor = vendor;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public GraphicsCard getGraphicsCard() {
		return this.graphicsCard;
	}

	public void setGraphicsCard(GraphicsCard graphicsCard) {
		this.graphicsCard = graphicsCard;
	}

	public Vendor getVendor() {
		return this.vendor;
	}

	public void setVendor(Vendor vendor) {
		this.vendor = vendor;
	}

}
