package com.bar3.hibernateDemo;

// Generated 2016-2-7 13:28:22 by Hibernate Tools 4.3.1

/**
 * Customer generated by hbm2java
 */
public class Customer implements java.io.Serializable {

	private long id;
	private String name;
	private Address homeAddress;
	private Address comAddress;

	public Customer() {
	}

	public Customer(String name, Address homeAddress, Address comAddress) {
		this.name = name;
		this.homeAddress = homeAddress;
		this.comAddress = comAddress;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Address getHomeAddress() {
		return this.homeAddress;
	}

	public void setHomeAddress(Address homeAddress) {
		this.homeAddress = homeAddress;
	}

	public Address getComAddress() {
		return this.comAddress;
	}

	public void setComAddress(Address comAddress) {
		this.comAddress = comAddress;
	}

}
