package com.bar3.hibernateDemo;

// Generated 2016-2-7 13:50:38 by Hibernate Tools 4.3.1

/**
 * GraphicsCard generated by hbm2java
 */
public class GraphicsCard implements java.io.Serializable {

	private String type;

	public GraphicsCard() {
	}

	public GraphicsCard(String type) {
		this.type = type;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

}
