package com.bar3.hibernateDemo;

// Generated 2016-2-7 13:50:38 by Hibernate Tools 4.3.1

/**
 * Vendor generated by hbm2java
 */
public class Vendor implements java.io.Serializable {

	private long id;
	private String type;

	public Vendor() {
	}

	public Vendor(String type) {
		this.type = type;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

}
